name: Builds JAR
on:
    push:
        branches:
            - master
jobs:
    gradle:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: temurin
                  java-version: 17.0.5
            - name: Setup gradle
              uses: gradle/gradle-build-action@v2

            - name: Execute gradle build
              run: ./gradlew build

            - name: Execute gradle jar
              run: ./gradlew fatJar

            - name: Upload jar
              uses: actions/upload-artifacts@v3
              with:
                  name: tp1-all-1.0.0-SNAPSHOT.jar
                  path: build/libs/tp1-all-1.0.0-SNAPSHOT.jar
